"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[866],{27205:function(re,y,n){n.r(y),n.d(y,{default:function(){return ne}});var N=n(5574),I=n.n(N),O=n(51431),M=n(68400),v=n.n(M),f=n(68479),b=n(9361),S,p,D,w=function(){var i=b.Z.useToken,a=i(),t=a.token,r="300px";return{homePage:(0,f.iv)(S||(S=v()([`
      height: 100vh;
      overflow: hidden;
    `]))),sidePanel:(0,f.iv)(p||(p=v()([`
      width: `,`;
      box-shadow: `,`;
    `])),r,t.boxShadow),content:(0,f.iv)(D||(D=v()([`
      width: calc(100% - `,`);
      background: `,`;
    `])),r,t.colorBgLayout)}},B=n(91213),u=n(67294),G=n(31989),H=n(97857),c=n.n(H),d=n(44422),V={width:428,height:926,posterImg:"",title:"",role:"",username:"",time:"",roleImg:""},se="YYYY-MM-DD",F=(0,u.createContext)({render:void 0,canvas:void 0,size:{width:0,height:0},config:V}),T=function(){var i=(0,u.useContext)(F),a=i.size,t=i.config,r=(0,u.useMemo)(function(){return{x:(a.width-t.width)/2,y:(a.height-t.height)/2}},[a,t.width,t.height]);return c()({offset:r},i)},e=n(85893),Y=function(){var i=T(),a=i.offset,t=i.config,r=t.width,s=t.height,l=t.posterImg;return(0,e.jsxs)(e.Fragment,{children:[(0,e.jsx)(d.UL,c()(c()({width:r,height:s},a),{},{fill:"#fff"})),(0,e.jsx)(d.Ee,c()({img:l,width:r,keepAspectRatio:!0},a),l)]})},U=Y,x=32,g=16,P=310,Z=100,W=200,X=function(){var i=T(),a=i.offset,t=i.config,r=t.width,s=t.height,l=t.title,z=t.role,ae=t.username,ie=t.time,m=t.roleImg,C=a.x+x,A=a.y+s-P-x,L=r-x*2;return(0,e.jsxs)(e.Fragment,{children:[(0,e.jsx)(d.UL,{width:L,height:P,x:C,y:A,fill:"#fff",radius:8,opacity:.9}),(0,e.jsx)(d.xv,{text:l,x:C+g,y:A+g,textBaseline:"top"}),m&&(0,e.jsx)(d.Ee,{img:m,x:C+L-Z-g,y:A+g,width:Z,height:W})]})},$=X,Q=new G.Th,J=function(i){var a,t=i.config,r=(0,u.useRef)(null),s=(a=(0,B.Z)(r))!==null&&a!==void 0?a:{width:0,height:0},l=(0,u.useRef)(Q);return(0,e.jsx)("div",{style:{width:"100%",height:"100%"},id:"container",ref:r,children:(0,e.jsx)(d.Xz,{width:s==null?void 0:s.width,height:s==null?void 0:s.height,renderer:l.current,children:(0,e.jsx)(F.Provider,{value:{canvas:void 0,render:void 0,size:s,config:t},children:(0,e.jsxs)(d.ZA,{transform:"scale(0.8)",children:[(0,e.jsx)(U,{}),(0,e.jsx)($,{})]})})})})},K=J,E,k=function(){return{counterfoilSidebar:(0,f.iv)(E||(E=v()([`
      height: 100%;
      padding: 32px 16px;
    `])))}},h=n(14126),j=n(6084),q=n(27484),_=n.n(q),oe=n(33852);_().locale("zh-cn");var ee=function(i){var a=i.config,t=i.setConfig,r=k(),s=h.Z.useForm(),l=I()(s,1),z=l[0];return(0,e.jsx)("div",{className:r.counterfoilSidebar,children:(0,e.jsxs)(h.Z,{form:z,initialValues:a,labelAlign:"left",labelCol:{span:6},wrapperCol:{span:18},onValuesChange:function(ie,m){t(m)},children:[(0,e.jsx)(h.Z.Item,{label:"\u5267\u672C\u540D",name:"title",children:(0,e.jsx)(j.Z,{placeholder:"\u8BF7\u8F93\u5165\u5267\u672C\u540D\u79F0"})}),(0,e.jsx)(h.Z.Item,{label:"\u89D2\u8272",name:"role",children:(0,e.jsx)(j.Z,{placeholder:"\u8BF7\u8F93\u5165\u89D2\u8272\u540D"})}),(0,e.jsx)(h.Z.Item,{label:"\u59D3\u540D",name:"username",children:(0,e.jsx)(j.Z,{placeholder:"\u8BF7\u8F93\u5165\u59D3\u540D"})})]})})},te=ee,R={width:428,height:926,posterImg:"https://mdn.alipayobjects.com/huamei_baaa7a/afts/img/A*h6p8S76U58IAAAAAAAAAAAAADqSCAQ/original",title:"\u89C2\u767D\u89C9\u559C",role:"\u50BB\u5B50",username:"\u6D1B\u7430",time:"2023-12-22",roleImg:"https://pic.imgdb.cn/item/658afb19c458853aefba3146.jpg"};function ne(){var o=w(),i=(0,u.useState)(R),a=I()(i,2),t=a[0],r=a[1];return(0,e.jsxs)(O.Z,{className:o.homePage,children:[(0,e.jsx)("div",{className:o.sidePanel,children:(0,e.jsx)(te,{config:t,setConfig:r})}),(0,e.jsx)("div",{className:o.content,children:(0,e.jsx)(K,{config:R})})]})}}}]);
